"""Prompt construction and response guardrails for POST /forecast/explain.

Step 1 (the context dict) comes from explain_context.py; Step 3 (the raw
Azure OpenAI call) comes from llm_client.py. This module owns Step 2
(building the prompt from that context) and Step 4 (validating/repairing
the LLM's structured response before anything reaches the API caller).
"""

import json
import logging
import re
from typing import Any, Optional

from src.genai.llm_client import call_chat_json

logger = logging.getLogger("sales_forecasting_api.explain")

SYSTEM_PROMPT = """You are explaining a sales forecast that has ALREADY been generated by a machine learning model. You do not generate, change, or restate a different forecast number than the ones given to you in the context.

Only reference facts present in the JSON context provided in the user message. Do not invent statistics, dates, percentages, or numbers that are not present in that context.

If a user question is given and the context does not contain enough information to answer it, say so explicitly rather than guessing.

Respond with a single JSON object with exactly these keys and no others:
{
  "explanation": "string - plain language summary",
  "key_drivers": ["string", ...],
  "risks_or_opportunities": ["string", ...],
  "recommendation": "string"
}
Return nothing except this JSON object."""

REQUIRED_KEYS = {"explanation", "key_drivers", "risks_or_opportunities", "recommendation"}

_NUMBER_PATTERN = re.compile(r"-?\d+\.?\d*")


def _build_user_message(context: dict[str, Any], user_question: Optional[str]) -> str:
    instruction = (
        f"Answer this specific question using only the context above: {user_question}"
        if user_question
        else "No specific question was asked -- produce a general explanation of this forecast."
    )
    return (
        "Context (the only facts you may reference):\n"
        f"{json.dumps(context, indent=2, default=str)}\n\n"
        f"{instruction}"
    )


def _parse_and_validate(raw_content: str) -> Optional[dict[str, Any]]:
    try:
        parsed = json.loads(raw_content)
    except (json.JSONDecodeError, TypeError):
        return None

    if not isinstance(parsed, dict) or not REQUIRED_KEYS.issubset(parsed.keys()):
        return None
    if not isinstance(parsed["explanation"], str) or not isinstance(parsed["recommendation"], str):
        return None
    if not isinstance(parsed["key_drivers"], list) or not isinstance(parsed["risks_or_opportunities"], list):
        return None

    return {
        "explanation": parsed["explanation"],
        "key_drivers": [str(item) for item in parsed["key_drivers"]],
        "risks_or_opportunities": [str(item) for item in parsed["risks_or_opportunities"]],
        "recommendation": parsed["recommendation"],
    }


def _check_numeric_grounding(explanation: str, context: dict[str, Any]) -> None:
    """Log a warning (never raises) if the explanation contains a number that
    doesn't appear anywhere in the context dict. Approximate on purpose --
    exact numeric matching (rounding, formatting) is hard to do perfectly."""

    context_numbers = set(_NUMBER_PATTERN.findall(json.dumps(context, default=str)))
    explanation_numbers = set(_NUMBER_PATTERN.findall(explanation))

    ungrounded = explanation_numbers - context_numbers
    if ungrounded:
        logger.warning("LLM explanation contains numbers not found in context: %s", sorted(ungrounded))


def _fallback_explanation(context: dict[str, Any]) -> dict[str, Any]:
    """Generic templated explanation built purely from context, used when the
    LLM response can't be parsed/validated even after a retry -- the request
    must never fail just because the LLM misbehaved."""

    key_drivers = []
    if context["recent_actuals"].get("trend_28d") is not None:
        direction = "up" if context["recent_actuals"]["trend_28d"] >= 0 else "down"
        key_drivers.append(f"The 28-day sales trend is currently trending {direction}.")
    if context["promotion"]["promotion_flag"]:
        key_drivers.append("A promotion was active as of the most recent observed data.")
    if not key_drivers:
        key_drivers.append("Recent sales history and seasonality patterns.")

    risks = []
    if context["holidays_in_forecast_window"]:
        names = ", ".join(h["name"] for h in context["holidays_in_forecast_window"])
        risks.append(f"Holiday(s) fall within the forecast window ({names}), which may shift demand.")
    if not risks:
        risks.append("No specific risks identified from the available context.")

    change = context.get("vs_recent_history_pct_change")
    change_text = (
        f"{change:+.1f}% versus the trailing 28-day average"
        if change is not None
        else "an amount that couldn't be compared to recent history"
    )

    explanation = (
        f"Over the next {context['forecast_horizon_days']} days, the model predicts an average of "
        f"{context['avg_predicted_units']} units/day ({context['total_predicted_units']} total) for "
        f"product {context['product_id']} at store {context['store_id']}, {change_text}."
    )

    return {
        "explanation": explanation,
        "key_drivers": key_drivers,
        "risks_or_opportunities": risks,
        "recommendation": "Monitor actuals against this forecast and adjust inventory/staffing plans accordingly.",
    }


def generate_explanation(context: dict[str, Any], user_question: Optional[str]) -> dict[str, Any]:
    """Run Steps 2-4: build the prompt, call the LLM, validate/repair its
    response, and return the four narrative fields (explanation, key_drivers,
    risks_or_opportunities, recommendation).

    Never raises for a malformed LLM response -- falls back to a templated
    explanation instead. Network/credential failures from the LLM call
    itself DO propagate, so the caller can turn them into a clean 503.
    """

    user_message = _build_user_message(context, user_question)

    for attempt in range(2):
        raw_content = call_chat_json(SYSTEM_PROMPT, user_message)
        parsed = _parse_and_validate(raw_content)
        if parsed is not None:
            _check_numeric_grounding(parsed["explanation"], context)
            return parsed
        logger.warning("LLM response failed validation on attempt %d: %r", attempt + 1, raw_content)

    logger.warning("LLM response failed validation twice; falling back to templated explanation.")
    return _fallback_explanation(context)
